  apiVersion: apps/v1
kind: Deployment
metadata:
  name: templateapp
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: templateapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: templateapp
    spec:
      serviceAccountName: {{ .Values.WORKLOAD_ID.NAME }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000  
        supplementalGroups: [2000]
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: templateapp
        image:  {{ print .Values.ACR_NAME "/" .Values.APP_NAME ":" .Values.GIT_COMMIT_VERSION }} 
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false  
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            memory: "128Mi"
            cpu: "0.5"
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "ric"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: templateapp-svc
  namespace: {{ .Values.NAMESPACE }}
  {{ .Values.SERVICES.ANNOTATIONS }}
spec:
  selector:
    app: templateapp
  ports:
  - port: 80
    targetPort: 80
  type: {{ .Values.SERVICES.TYPE }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  templateapp-vs
  namespace: apps
spec:
  hosts:
  -  httpbin.bjdazure.tech
  gateways:
  -  aks-istio-ingress/default-bjdazure-tech-gw
  http:
  - route:
    - destination:
        host: templateapp-svc
        port:
          number: 80