  apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.APP.NAME }}
  namespace: {{ .Values.APP.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.APP.NAME }}
      name: {{ .Values.APP.TAG_NAME }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ .Values.APP.NAME }}
        name: {{ .Values.APP.TAG_NAME }}
    spec:
      serviceAccountName: {{ .Values.WORKLOAD_ID.NAME }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000  
        supplementalGroups: [2000]
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: {{ .Values.APP.NAME }}
        image:  {{ print .Values.ACR.NAME "/" .Values.APP.NAMESPACE "/" .Values.APP.NAME ":" .Values.APP.VERSION }} 
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false  
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            memory: "128Mi"
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ print .Values.APP.NAME "-svc" }}
  namespace: {{ .Values.APP.NAMESPACE }}
spec:
  selector:
    app: {{ .Values.APP.NAME }}
    name: {{ .Values.APP.TAG_NAME }}
  ports:
  - port: 80
    targetPort: {{ .Values.APP.PORT }}
  type: ClusterIP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  {{ print .Values.APP.NAME "-vs" }}
  namespace: {{ .Values.APP.NAMESPACE }}
spec:
  hosts:
  -  {{ .Values.APP.URL }}
  gateways:
  -  {{ .Values.ISTIO.GATEWAY }}
  http:
  - route:
    - destination:
        host: {{ print .Values.APP.NAME "-svc" }}
        port:
          number: 80