apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ISTIO.WORKLOAD_ID_NAME }}
  namespace: {{ .Values.ISTIO.NAMESPACE }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.ISTIO.CLIENT_ID }} 
    azure.workload.identity/tenant-id: {{ .Values.ISTIO.TENANT_ID }} 
  labels:
    azure.workload.identity/use: "true"