apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: istio-tls
  namespace: {{ .Values.ISTIO.NAMESPACE }}
spec:
  provider: azure
  secretObjects:                               
  - secretName: istio-ingress-tls
    type: kubernetes.io/tls
    data: 
    - objectName: wildcard-certificate
      key: tls.key
    - objectName: wildcard-certificate
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: {{ .Values.ISTIO.KEYVAULT_NAME }} 
    clientID: {{ .Values.ISTIO.CLIENT_ID }} 
    cloudName: ""                                         
    objects:  |
      array:
        - |
          objectName: wildcard-certificate
          objectType: secret
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: {{ .Values.ISTIO.TENANT_ID }} 