---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: {{ .Values.OTEL.NAMESPACE }}
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            
      zipkin:
        endpoint: 0.0.0.0:9411

    processors:
      batch:

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    exporters:
      debug:
        verbosity: detailed

      azuremonitor:
        connection_string: {{ print "InstrumentationKey=" .Values.APP_INSIGHTS.INSTRUMENTATION_KEY ";IngestionEndpoint=http://localhost:" .Values.OTEL.PROXY_LISTENING_PORT | quote  }}
        maxbatchsize: 10
        maxbatchinterval: 5s

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp,zipkin]
          processors: [batch]
          exporters: [debug,azuremonitor]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug,azuremonitor]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug,azuremonitor]
---