---
# Source: roman-coin-analyzer-infra/templates/otel-deployment.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: otel-system
---
# Source: roman-coin-analyzer-infra/templates/istio-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingress-sa-identity
  namespace: aks-istio-ingress
  annotations:
    azure.workload.identity/client-id: 7dd63771-7e29-4b62-b599-d33385a5d734 
    azure.workload.identity/tenant-id: 16b3c013-d300-468d-ac64-7eda0820b6d3 
  labels:
    azure.workload.identity/use: "true"
---
# Source: roman-coin-analyzer-infra/templates/otel-serviceaccount.yal
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oriole-12998-otel-identity
  namespace: otel-system
  annotations:
    azure.workload.identity/client-id: bb98f667-ee64-4bcf-aba5-98c6e53e2a71
    azure.workload.identity/tenant-id: 16b3c013-d300-468d-ac64-7eda0820b6d3
  labels:
    azure.workload.identity/use: "true"
---
# Source: roman-coin-analyzer-infra/templates/otel-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: otel-system
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            
      zipkin:
        endpoint: 0.0.0.0:9411

    processors:
      batch:

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    exporters:
      debug:
        verbosity: detailed

      azuremonitor:
        connection_string: "InstrumentationKey=fe3bbb23-090a-467c-953a-441109673dd9;IngestionEndpoint=http://localhost:8082"
        maxbatchsize: 10
        maxbatchinterval: 5s

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp,zipkin]
          processors: [batch]
          exporters: [debug,azuremonitor]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug,azuremonitor]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug,azuremonitor]
---
# Source: roman-coin-analyzer-infra/templates/otel-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: otel-system
  labels:
    component: otel-collector
spec:
  ports:
  - name: grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    component: otel-collector
---
# Source: roman-coin-analyzer-infra/templates/otel-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: otel-system
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: oriole-12998-otel-identity
      containers:
      - name: azuremonitor-ingestion-proxy
        image: "mcr.microsoft.com/azuremonitor/auth-proxy/prod/aad-auth-proxy/images/aad-auth-proxy:0.1.0-main-04-10-2024-7067ac84"  
        ports:
        - name: auth-port
          containerPort: 8082
        env:
          - name:  AUDIENCE
            value: https://monitor.azure.com/.default
          - name:  TARGET_HOST
            value: https://eastus2-3.in.applicationinsights.azure.com
          - name:  LISTENING_PORT
            value: "8082"
          - name:  AZURE_CLIENT_ID
            value: bb98f667-ee64-4bcf-aba5-98c6e53e2a71
          - name:  AZURE_TENANT_ID
            value: 16b3c013-d300-468d-ac64-7eda0820b6d3
        livenessProbe:
          httpGet:
            path: /health
            port: auth-port
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: auth-port
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi        
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.100.0
        command:
        - "/otelcol-contrib"
        - "--config=/config/otel-collector-config.yaml"
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
          - containerPort: 9411
          - containerPort: 4317
          - containerPort: 13133
        livenessProbe:
          httpGet:
            path: /
            port: 13133
        readinessProbe:
          httpGet:
            path: /
            port: 13133
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: otel-collector-config
          items:
          - key: "otel-collector-config.yaml"
            path: "otel-collector-config.yaml"
---
# Source: roman-coin-analyzer-infra/templates/istio-secretsprovider.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: istio-tls
  namespace: aks-istio-ingress
spec:
  provider: azure
  secretObjects:                               
  - secretName: istio-ingress-tls
    type: kubernetes.io/tls
    data: 
    - objectName: wildcard-certificate
      key: tls.key
    - objectName: wildcard-certificate
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: oriole12998kv 
    clientID: 7dd63771-7e29-4b62-b599-d33385a5d734 
    cloudName: ""                                         
    objects:  |
      array:
        - |
          objectName: wildcard-certificate
          objectType: secret
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: 16b3c013-d300-468d-ac64-7eda0820b6d3
